name: Prod workflow - Build and deploy to production

on:
  # Runs on closed pull request targeting the main branch
  pull_request:
    types:
      - closed
    branches:
      - main

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Deployment jobs
  deploy_job:
    runs-on: ubuntu-latest

    steps:
      - name: Connect to vps, update code & run docker
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          script: |
            # Check if project exist
            if [ -d "kanban" ]; then
              cd kanban
              docker compose -f compose.prod.yml down
              git pull origin main
              docker compose -f compose.prod.yml up --build -d
            else
              git clone git@github.com-personal:clement-jny/kanban.git
              cd kanban
              docker compose -f compose.prod.yml up --build -d
            fi
