name: Prod workflow - Build and deploy to production

on:
  # Runs on closed pull request targeting the main branch
  pull_request:
    types:
      - closed
    branches:
      - main

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Deployment jobs
  deploy_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2 
      
      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Delete current version of project
        run: |
          ssh -o StrictHostKeyChecking=no -T ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} << 'EOF'
            cd kanban
            docker compose -f compose.prod.yml down
            rm -rf *
          EOF

      # Transfer the code to the VPS via SCP (Secure Copy)
      - name: Transfer code to VPS
        run: |
          scp -o StrictHostKeyChecking=no -r . ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }}:kanban

      # - name: Deploy to Production Server
      #   run: |
      #     ssh -o StrictHostKeyChecking=no -T ${{ secrets.VPS_USER }}@${{ secrets.VPS_IP }} << 'EOF'
      #       cd kanban
      #       docker compose -f compose.prod.yml up --build -d
      #     EOF
